# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DistanceConverter": "00_base.ipynb",
         "hatchbox": "00_base.ipynb",
         "merge_MultiLineStrings": "00_base.ipynb",
         "morsify": "00_base.ipynb",
         "add_jittered_midpoints": "00_base.ipynb",
         "LineString_to_jittered_bezier": "00_base.ipynb",
         "get_random_points_in_polygon": "00_base.ipynb"}

modules = ["base.py"]

doc_url = "https://anaka.github.io/oned/"

git_url = "https://github.com/anaka/oned/tree/master/"

def custom_doc_links(name): return None
